server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true